version: '3.3'

services:
  keycloak:
    image: jboss/keycloak
    restart: always
    ports:
    - "8180:8080"
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: password
  rabbit:
    image: rabbitmq:3.8.19
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password
    hostname: localhost
  mongo:
    image: mongo
    restart: always
    ports:
      - 8087:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGODB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_PASS}
      MONGO_INITDB_DATABASE: ${MONGODB_DATABASE}
  postgre:
    image: postgres:12
    restart: always
    ports:
      - 8085:5432
    environment:
      POSTGRES_USER: ${POSTGRE_USER}
      POSTGRES_PASSWORD: ${POSTGRE_PASS}
      POSTGRES_DB: order-service