spring:
  application:
    name: order-service
  datasource:
    username: ${POSTGRE_USER}
    password: ${POSTGRE_PASS}
    url: jdbc:postgresql://localhost:8085/order-service
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 0

eureka:
  instance:
    instance-id: ${spring.application.name}:${random.uuid}
